BASE_VALIDATIONS = (
    'additionalItems',
    'additionalProperties',
    'allOf',
    'anyOf',
    'bsonType',
    'dependencies',
    'description',
    'enum',
    'exclusiveMaximum',
    'exclusiveMinimum',
    'items',
    'maximum',
    'maxItems',
    'maxLength',
    'maxProperties',
    'minimum',
    'minItems',
    'minLength',
    'minProperties',
    'multipleOf',
    'not',
    'oneOf',
    'pattern',
    'patternProperties',
    'properties',
    'required',
    'title',
    'type',
    'uniqueItems',
)



